name: build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy static content to s3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install dependencies
      run: yarn install

    - name: Build static content
      run: yarn build

    - name: Copy files to S3
      if: github.ref == 'refs/heads/main'
      run: aws s3 sync --delete build/ s3://rammahgon/help/
